### PR TITLE
Add files via upload

### LINKED ISSUE #29: Hacktoberfest 2022! 🎉
It's that time of the year again!
Hacktoberfest is back with its 11th edition this year. If you are a participant and want to add to the pool of scripts we've collected here, jump right in!

Make sure you read the [contributing.md](https://github.com/SVijayB/PyHub/blob/master/.github/CONTRIBUTING.md) file.

Also, once you add all the programs, make sure you update the readme.md file accordingly. If the program belongs to none of the already existing categories, add it to the miscellaneous section.

**Happy hacking!** 🎉 🚀

### PR DESCRIPTION
**Pull request by manishtambe**
Added Cycle Detection In Linked List Problem & Palindrome Checker Problem In The Miscellaneous !

### Related Issue

This PR closes #29 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by SVijayB** [comment]
Hey @manishtambe it would be great if you could move the programs into the `Data_Structures` directory. I'll merge the PR once that's done

**Comment by manishtambe** [comment]
ok I will do that right now !

**Comment by manishtambe** [comment]
Done Can you please check ?

**Comment by SVijayB** [comment]
@manishtambe I don't think the changes were committed, could you please check again?

**Comment by SVijayB** [comment]
Alright, merging! Thanks for contributing to the repository 🚀

**Comment by manishtambe** [comment]
Can you please check now ?

**Comment by manishtambe** [comment]
Can you please add label as "hacktoberfest" accepted label ?

**Comment by manishtambe** [comment]
@SVijayB can you please add "hacktoberfest - accepted" label  to this PR?

**Pull request merged**
