### PR TITLE
Create Detect cycle in an undirected graph (using DFS).java

### PR DESCRIPTION
**Pull request by krushnadurole**
### Related Issue

This PR closes # 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by krushnadurole** [comment]
#41 added

**Comment by SVijayB** [comment]
@krushnadurole can you update the README.md file and then I'll have the PR merged.

**Comment by krushnadurole** [comment]
@SVijayB i have updated readme file , please merge

**Comment by SVijayB** [comment]
Hey @krushnadurole can you update the README file in the same PR instead of creating another. Just update in this PR and commit.

**Comment by krushnadurole** [comment]
#43 readme file updated

**Comment by SVijayB** [comment]
@krushnadurole I meant, update the README file in the same pull request, in the same branch, and commit. Do not send a separate pull request for it. It's just spammy.

**Pull request merged**
